spring.application.name=JWT_SpringBoot

# Server
server.port=8080

# JWT Config
application.security.jwt.secret-key=McvbIKwPaVjhmKBwFUdHDXzvfWeAZgaaJ8Xr6cBsvNkP19VUvAWw7GzFMV6ZhHsI
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_spring
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
